import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'node:path';
// Type-only import: pulls in vite-react-ssg's `declare module 'vite'` augmentation
// so `ssgOptions` is recognised on the Vite config.
import type {} from 'vite-react-ssg';

// Multi-page build: the public storefront (index.html, statically generated by
// vite-react-ssg) and the admin panel (admin/index.html → served at /admin/,
// stays a client-rendered SPA and is noindex).
// `base` is '/' for the custom-domain (elezon.ru) build and '/elezon/' for the
// GitHub project-page preview, driven by VITE_BASE.
//
// The storefront ships a strict CSP via <meta> (GitHub Pages can't set headers),
// with `script-src 'self'` — no 'unsafe-inline'. vite-react-ssg emits small inline
// bootstrap scripts (router hydration data, build hash) that such a CSP blocks.
// Their sha256 hashes are added to each page's script-src by a postbuild step
// (scripts/inject-csp-hashes.mjs), which runs on the final HTML so the hashed
// bytes match exactly. The JSON state island (type="application/json") is
// non-executable and is left untouched.
export default defineConfig({
  base: process.env.VITE_BASE || '/',
  plugins: [react()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        admin: resolve(__dirname, 'admin/index.html'),
      },
    },
  },
  ssgOptions: {
    entry: 'src/main.tsx',
    dirStyle: 'nested',
    // beasties (critical-CSS inlining) is an optional peer we don't install.
    beastiesOptions: false,
  },
});
