/* ELEZON — seed generator. Emits supabase/seed.sql from the bundled demo data
   so the database matches what the prototype shows. Run with: node scripts/gen-seed.ts
   (Node 22.18+/23.6+ strips TypeScript automatically). Re-runnable; uses ON CONFLICT.
   Seeds catalog + content + settings + stats. Orders/customers/leads start empty. */

import { writeFileSync, mkdirSync } from 'node:fs';
import { ELEZON_DATA } from '../src/data/catalog.ts';
import { I18N_EN } from '../src/i18n/translations.ts';

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const arr = (xs) => 'ARRAY[' + xs.map(q).join(',') + ']::text[]';
const jsonb = (v) => "'" + JSON.stringify(v).replace(/'/g, "''") + "'::jsonb";
const num = (n) => (n == null ? 'null' : String(n));

const BRAND_META = {
  'ABB': { country: 'Швейцария', slug: 'abb' },
  'Schneider Electric': { country: 'Франция', slug: 'schneider-electric' },
  'Siemens': { country: 'Германия', slug: 'siemens' },
  'Theben': { country: 'Германия', slug: 'theben' },
  'JUNG': { country: 'Германия', slug: 'jung' },
  'Gira': { country: 'Германия', slug: 'gira' },
  'WAGO': { country: 'Германия', slug: 'wago' },
  'Phoenix Contact': { country: 'Германия', slug: 'phoenix-contact' },
  'Hager': { country: 'Германия / Швейцария', slug: 'hager' },
  'Legrand': { country: 'Франция', slug: 'legrand' },
  'Beckhoff': { country: 'Германия', slug: 'beckhoff' },
  'Carlo Gavazzi': { country: 'Италия', slug: 'carlo-gavazzi' },
};

const out = [];
out.push('-- ELEZON seed (generated by scripts/gen-seed.ts). Safe to re-run.');
out.push('');

// categories
out.push('insert into categories (id,name,short,code,count,"desc",sub,pos) values');
out.push(ELEZON_DATA.categories
  .map((c, i) => `(${q(c.id)},${q(c.name)},${q(c.short)},${q(c.code)},${c.count},${q(c.desc)},${arr(c.sub)},${i})`)
  .join(',\n') + '\non conflict (id) do nothing;');
out.push('');

// brands
out.push('insert into brands (id,name,country,slug,count,pos) values');
out.push(ELEZON_DATA.brands
  .map((name, i) => {
    const m = BRAND_META[name] || { country: '', slug: name.toLowerCase().replace(/\s+/g, '-') };
    const count = ELEZON_DATA.products.filter((p) => p.brand === name).length;
    return `(${q(m.slug)},${q(name)},${q(m.country)},${q(m.slug)},${count},${i})`;
  })
  .join(',\n') + '\non conflict (id) do nothing;');
out.push('');

// products
out.push('insert into products (id,name,cat,brand,type,article,price,stock,qty,specs,pos) values');
out.push(ELEZON_DATA.products
  .map((p, i) => `(${q(p.id)},${q(p.name)},${q(p.cat)},${q(p.brand)},${q(p.type)},${q(p.article)},${num(p.price)},${q(p.stock)},${p.qty},${jsonb(p.specs)},${i})`)
  .join(',\n') + '\non conflict (id) do nothing;');
out.push('');

// site_stats (bilingual)
out.push('insert into site_stats (idx,v,l,v_en,l_en) values');
out.push(ELEZON_DATA.stats
  .map((s, i) => `(${i},${q(s.v)},${q(s.l)},${q(I18N_EN[s.v] || s.v)},${q(I18N_EN[s.l] || s.l)})`)
  .join(',\n') + '\non conflict (idx) do nothing;');
out.push('');

// content singleton
out.push(`insert into content (id,home_sub,about_heading,about_body,delivery_body,contact_address,contact_phone,contact_email,requisites) values
(1,
 ${q('КИП, низковольтное оборудование и KNX оригинальных брендов. Склад в Москве, отгрузка за 24 часа.')},
 ${q('Инженерная поставка электротехнического оборудования')},
 ${q('ELEZON — поставщик оборудования для автоматизации зданий, КИП, низковольтных систем и KNX. Мы соединяем инженерную экспертизу с надёжной логистикой.')},
 ${q('Работаем по договору с полным пакетом документов. Отгрузка со склада в Москве в течение суток.')},
 ${q('121087, Москва, ул. Большая Филёвская, 4')},
 ${q('+7 (495) 147-47-61')},
 ${q('info@elezon.ru')},
 ${q('ООО «Элезон» · ИНН 7730812345 · КПП 773001001 · ОГРН 1167746000000')})
on conflict (id) do nothing;`);
out.push('');

// settings singleton
out.push(`insert into settings (id,store_name,email,phone,accent,default_lang,notify_new,price_no_vat,auto_publish) values
(1,${q('ELEZON')},${q('info@elezon.ru')},${q('+7 (495) 147-47-61')},${q('lime')},${q('ru')},true,false,true)
on conflict (id) do nothing;`);
out.push('');

mkdirSync('supabase', { recursive: true });
writeFileSync('supabase/seed.sql', out.join('\n'));
console.log('Wrote supabase/seed.sql');
